/**
 * Oh My Course API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CreateTestRequestDto } from './createTestRequestDto';
import { CreateTextContentRequestDto } from './createTextContentRequestDto';

export interface CreateLessonMaterialRequestDto { 
    type: CreateLessonMaterialRequestDto.TypeEnum;
    mediaId: number;
    textContent: CreateTextContentRequestDto;
    test: CreateTestRequestDto;
}
export namespace CreateLessonMaterialRequestDto {
    export type TypeEnum = 'audio' | 'video' | 'text' | 'test';
    export const TypeEnum = {
        Audio: 'audio' as TypeEnum,
        Video: 'video' as TypeEnum,
        Text: 'text' as TypeEnum,
        Test: 'test' as TypeEnum
    };
}