/**
 * Oh My Course API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MediaResponseDto } from './mediaResponseDto';
import { TestResponseDto } from './testResponseDto';
import { TextContentResponseDto } from './textContentResponseDto';

export interface LessonMaterialResponseDto { 
    readonly id: number;
    readonly type: LessonMaterialResponseDto.TypeEnum;
    media: MediaResponseDto;
    textContent: TextContentResponseDto;
    test: TestResponseDto;
}
export namespace LessonMaterialResponseDto {
    export type TypeEnum = 'audio' | 'video' | 'text' | 'test';
    export const TypeEnum = {
        Audio: 'audio' as TypeEnum,
        Video: 'video' as TypeEnum,
        Text: 'text' as TypeEnum,
        Test: 'test' as TypeEnum
    };
}